import { PropertyTypeId } from "./propertyTypeIDs";

export const AMENITY_OPTIONS: Array<{ name: string; icon: string; types?: PropertyTypeId[] }> = [
  // Boarding (hotel)
  { name: "Individual kennel / private room", icon: "🧺", types: ["hotel"] },
  { name: "Shared room", icon: "🛏️", types: ["hotel"] },
  { name: "Luxury suite", icon: "🛋️", types: ["hotel"] },
  { name: "Size-based enclosures (small / medium / large pets)", icon: "📏", types: ["hotel"] },
  { name: "Indoor boarding", icon: "🏠", types: ["hotel"] },
  { name: "Outdoor access", icon: "🌿", types: ["hotel"] },
  { name: "Air-conditioned rooms", icon: "❄️", types: ["hotel"] },
  { name: "Heated rooms", icon: "🔥", types: ["hotel"] },
  { name: "Natural ventilation", icon: "🍃", types: ["hotel"] },
  { name: "Comfortable bedding provided", icon: "🧸", types: ["hotel"] },
  { name: "Owner-provided bedding allowed", icon: "🧺", types: ["hotel"] },
  { name: "Soundproof / quiet areas", icon: "🔇", types: ["hotel"] },
  { name: "24/7 staff supervision", icon: "👁️", types: ["hotel"] },
  { name: "Scheduled feeding", icon: "🍽️", types: ["hotel"] },
  { name: "Custom diet accommodation", icon: "🥣", types: ["hotel"] },
  { name: "Medication administration", icon: "💊", types: ["hotel"] },
  { name: "Vet-supervised boarding", icon: "⚕️", types: ["hotel"] },
  { name: "Special needs care", icon: "🫶", types: ["hotel"] },
  { name: "Daily walks", icon: "🚶", types: ["hotel"] },
  { name: "Group playtime", icon: "🐕", types: ["hotel"] },
  { name: "Solo playtime", icon: "🎾", types: ["hotel"] },
  { name: "Outdoor play yard", icon: "🏕️", types: ["hotel"] },
  { name: "Enrichment toys & activities", icon: "🧩", types: ["hotel"] },
  { name: "Secure fencing", icon: "🛡️", types: ["hotel"] },
  { name: "CCTV monitoring", icon: "📹", types: ["hotel"] },
  { name: "Regular sanitation", icon: "🧼", types: ["hotel"] },
  { name: "Vaccination required", icon: "✅", types: ["hotel"] },
  { name: "Separate cat and dog areas", icon: "🐶", types: ["hotel"] },
  { name: "Photo / video updates", icon: "📷", types: ["hotel"] },
  { name: "Live pet cam", icon: "📡", types: ["hotel"] },
  { name: "Emergency contact support", icon: "🆘", types: ["hotel"] },
  { name: "Long-stay discounts", icon: "🏷️", types: ["hotel"] },

  // Veterinary
  { name: "Consultation / exam rooms", icon: "🩺", types: ["veterinary"] },
  { name: "Diagnostic laboratory", icon: "🧪", types: ["veterinary"] },
  { name: "X-ray services", icon: "🦴", types: ["veterinary"] },
  { name: "Ultrasound services", icon: "📡", types: ["veterinary"] },
  { name: "Surgical suite", icon: "🏥", types: ["veterinary"] },
  { name: "Recovery / observation area", icon: "🛏️", types: ["veterinary"] },
  { name: "Isolation ward", icon: "🚪", types: ["veterinary"] },
  { name: "General check-ups", icon: "✅", types: ["veterinary"] },
  { name: "Vaccinations", icon: "💉", types: ["veterinary"] },
  { name: "Emergency care", icon: "🚑", types: ["veterinary"] },
  { name: "Dental services", icon: "🦷", types: ["veterinary"] },
  { name: "Minor procedures", icon: "🩹", types: ["veterinary"] },
  { name: "Major surgery", icon: "⚕️", types: ["veterinary"] },
  { name: "Chronic illness management", icon: "📋", types: ["veterinary"] },
  { name: "Licensed veterinarian on-site", icon: "👩‍⚕️", types: ["veterinary"] },
  { name: "Veterinary technicians", icon: "🧑‍⚕️", types: ["veterinary"] },
  { name: "24/7 emergency availability", icon: "🕐", types: ["veterinary"] },
  { name: "Appointment booking", icon: "📅", types: ["veterinary"] },
  { name: "Walk-in accepted", icon: "🚶", types: ["veterinary"] },
  { name: "Digital medical records", icon: "💾", types: ["veterinary"] },
  { name: "Online prescription refills", icon: "💊", types: ["veterinary"] },
  { name: "Health reminders", icon: "🔔", types: ["veterinary"] },
  { name: "Post-treatment follow-ups", icon: "☎️", types: ["veterinary"] },

  // Grooming
  { name: "Bath & blow-dry", icon: "🛁", types: ["grooming"] },
  { name: "Haircut / trimming", icon: "✂️", types: ["grooming"] },
  { name: "Breed-specific styling", icon: "🐩", types: ["grooming"] },
  { name: "Nail trimming", icon: "🧷", types: ["grooming"] },
  { name: "Ear cleaning", icon: "👂", types: ["grooming"] },
  { name: "Eye cleaning", icon: "👁️", types: ["grooming"] },
  { name: "De-shedding treatment", icon: "🧽", types: ["grooming"] },
  { name: "Medicated baths", icon: "🧴", types: ["grooming"] },
  { name: "Flea & tick treatment", icon: "🪲", types: ["grooming"] },
  { name: "Anal gland expression", icon: "🧼", types: ["grooming"] },
  { name: "Teeth brushing", icon: "🦷", types: ["grooming"] },
  { name: "Professional grooming tables", icon: "🪑", types: ["grooming"] },
  { name: "Dedicated bathing stations", icon: "🚿", types: ["grooming"] },
  { name: "Cage-free grooming", icon: "🐾", types: ["grooming"] },
  { name: "Low-stress handling", icon: "🌿", types: ["grooming"] },
  { name: "Separate drying area", icon: "💨", types: ["grooming"] },
  { name: "Hypoallergenic products", icon: "🧴", types: ["grooming"] },
  { name: "Sensitive-skin products", icon: "🌼", types: ["grooming"] },
  { name: "One-pet-at-a-time grooming", icon: "🐶", types: ["grooming"] },
  { name: "Vet-on-call for grooming", icon: "☎️", types: ["grooming"] },
  { name: "Same-day service", icon: "⚡", types: ["grooming"] },
  { name: "Appointment scheduling", icon: "📅", types: ["grooming"] },
  { name: "Grooming packages", icon: "🎁", types: ["grooming"] },
  { name: "Add-on spa services", icon: "🫧", types: ["grooming"] },
];