import { PropertyInitalData } from "../types/initial_types/propertyInitialData";

export const INITIAL_FORM_DATA: PropertyInitalData = {
  propertyName: "",
  addressSearch: "",
  addressLine2: "",
  country: "",
  city: "",
  zipCode: "",
  latitude: 14.5995,
  longitude: 120.9842,
  phone: "",
  ownerName: "",
  email: "",
  password: "",
  confirmPassword: "",
  description: "",
  services: [],
  petTypesAccepted: [],
  dogSizes: [],
  exoticPetTypes: "",
  breedRestrictions: false,
  breedRestrictionDetails: "",
  aggressivePolicy: false,
  aggressivePolicyDetails: "",
  unvaccinatedPolicy: false,
  unvaccinatedPolicyDetails: "",
  facilitiesAmenities: [],
  sameHoursEveryDay: false,
  dailyOpenTime: "",
  dailyCloseTime: "",
  weeklyHours: {},
  weekendAvailability: false,
  holidayAvailability: false,
  emergencyServices: false,
  checkInCutoff: "",
  pickupStart: "",
  pickupEnd: "",
  appointmentOnly: "",
  bookingRules: [],
  cancellationPolicy: { freeCancellation: "24hours", lateFee: "", noShow: "" },
  complianceRequirements: [],
  healthSafety: [],
  vetAvailability: [],
  sanitationProtocols: [],
  emergencyContact: "",
  nearestVetHospital: "",
  emergencyResponseTime: "",
  baseServices: [],
  petSizePricing: { small: "", medium: "", large: "", giant: "", cats: "", exotic: "" },
  addOns: [],
  vetFees: {},
  boardingRules: { advanceBooking: false, sameDayBooking: false, freeCancellation: false, lateCancellationFee: false, lateCancellationFeeAmount: "", vaccinationRequired: false, healthDeclaration: false, noAggressivePets: false, liabilityWaiver: false },
  feesCharges: { serviceFee: "", taxes: "Included", noShow: "", latePickup: "", cleaningFee: "", emergencyFee: "", holidaySurcharge: "", cancellationFee: "" },
  paymentOptions: { deposit: false, methods: [], refundPolicy: "", qrCodeGCash: "", qrCodePayMaya: "" },
  pricingNotes: "",
  additionalPricingNotes: "",
  propertyImages: [] as File[],
  lguPermits: [] as File[],
  baiDocument: null as File | null,
  contractDocument: null as File | null,
  occupancyRate: 0,
  animalCapacity: 0,
  serviceCapacities: [],
  legalEntityType: "" as "" | "individual" | "business",
  contractingParty: {
    firstName: "",
    middleName: "",
    lastName: "",
    email: "",
    phone: "",
    phoneCountryCode: "+63",
  },
  contractingPartyAddress: {
    country: "Philippines",
    streetAddress: "",
    addressLine2: "",
    city: "",
    postalCode: "",
  },
  legalAgreementAccepted: {
    termsAccepted: false,
    dataProcessing: false,
  },
  finalAgreementAccepted: false,
}